# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"listify": "utilities.ipynb",
         "reverse_dict": "utilities.ipynb",
         "del_dot": "utilities.ipynb",
         "del_zero": "utilities.ipynb",
         "expand_hyphen": "utilities.ipynb",
         "expand_star": "utilities.ipynb",
         "expand_colon": "utilities.ipynb",
         "expand_regex": "utilities.ipynb",
         "expand_code": "utilities.ipynb",
         "expand_columns": "utilities.ipynb",
         "format_codes": "utilities.ipynb",
         "insert_external": "utilities.ipynb",
         "sankey_format": "pattern_finder.ipynb",
         "stringify_durations": "pattern_finder.ipynb",
         "interleave_strings": "pattern_finder.ipynb",
         "left_justify": "pattern_finder.ipynb",
         "overlay_strings": "pattern_finder.ipynb",
         "shorten": "pattern_finder.ipynb",
         "shorten_interleaved": "pattern_finder.ipynb",
         "stringify_order": "pattern_finder.ipynb",
         "del_repeats": "pattern_finder.ipynb",
         "del_singles": "pattern_finder.ipynb",
         "stringify_time": "pattern_finder.ipynb",
         "make_codes": "utilities.ipynb",
         "make_data": "utilities.ipynb",
         "get_rows": "utilities.ipynb",
         "extract_codes": "utilities.ipynb",
         "Info": "utilities.ipynb",
         "memory": "utilities.ipynb",
         "unique": "utilities.ipynb",
         "count_codes": "utilities.ipynb",
         "lookup_codes": "utilities.ipynb",
         "get_codes": "utilities.ipynb"}

modules = ["tutorial.py",
           "old.py",
           "pattern.py",
           "utils.py"]

doc_url = "https://hmelberg.github.io/pattern_finder/"

git_url = "https://github.com/hmelberg/pattern_finder/tree/master/"

def custom_doc_links(name): return None
