# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Info": "pattern_finder.ipynb",
         "memory": "pattern_finder.ipynb",
         "listify": "pattern_finder.ipynb",
         "unique": "pattern_finder.ipynb",
         "del_dot": "pattern_finder.ipynb",
         "del_zero": "pattern_finder.ipynb",
         "expand_hyphen": "pattern_finder.ipynb",
         "expand_star": "pattern_finder.ipynb",
         "expand_colon": "pattern_finder.ipynb",
         "expand_regex": "pattern_finder.ipynb",
         "expand_code": "pattern_finder.ipynb",
         "expand_columns": "pattern_finder.ipynb",
         "get_rows": "pattern_finder.ipynb",
         "make_codes": "pattern_finder.ipynb",
         "make_data": "pattern_finder.ipynb",
         "extract_codes": "pattern_finder.ipynb",
         "sankey_format": "pattern_finder.ipynb",
         "persons_with": "pattern_finder.ipynb",
         "stringify_durations": "pattern_finder.ipynb",
         "interleave_strings": "pattern_finder.ipynb",
         "left_justify": "pattern_finder.ipynb",
         "overlay_strings": "pattern_finder.ipynb",
         "shorten": "pattern_finder.ipynb",
         "shorten_interleaved": "pattern_finder.ipynb",
         "stringify_order": "pattern_finder.ipynb",
         "del_repeats": "pattern_finder.ipynb",
         "del_singles": "pattern_finder.ipynb",
         "stringify_time": "pattern_finder.ipynb",
         "insert_external": "pattern_finder.ipynb"}

modules = ["core.py"]

doc_url = "https://hmelberg.github.io/pattern_finder/"

git_url = "https://github.com/hmelberg/pattern_finder/tree/master/"

def custom_doc_links(name): return None
